# Generated by Django 5.0.3 on 2024-03-29 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PageVisits',
            fields=[
                ('pagevisit_token', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('page_path', models.TextField()),
                ('start_time', models.TextField()),
                ('end_time', models.TextField(null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sessions')),
            ],
        ),
        migrations.CreateModel(
            name='MouseMovements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('text_or_tag_hovered', models.TextField()),
                ('recorded_at', models.TextField()),
                ('pagevisit_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pagevisits')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sessions')),
            ],
        ),
        migrations.CreateModel(
            name='LLMResponses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('response', models.TextField()),
                ('recorded_at', models.TextField()),
                ('is_emitted', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sessions')),
            ],
        ),
    ]
