# Generated by Django 5.0.3 on 2024-04-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_name', models.CharField(max_length=100)),
                ('display_title', models.CharField(max_length=100)),
                ('display_description', models.TextField()),
                ('is_discount', models.BooleanField(default=False)),
                ('discount_percent', models.FloatField(blank=True, null=True)),
                ('discount_dollars', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
