# Generated by Django 5.0.3 on 2024-04-01 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_adduserkey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotions',
            old_name='impulse_user',
            new_name='django_user_id',
        ),
        migrations.RenameField(
            model_name='sessions',
            old_name='impulse_user',
            new_name='django_user_id',
        ),
        migrations.CreateModel(
            name='ImpulseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('is_domain_configured', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
