# Generated by Django 5.0.3 on 2024-04-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_django_user_id_promotions_django_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotions',
            name='is_discount',
        ),
        migrations.AddField(
            model_name='promotions',
            name='ai_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotions',
            name='ai_discount_dollars_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotions',
            name='ai_discount_dollars_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotions',
            name='ai_discount_percent_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotions',
            name='ai_discount_percent_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotions',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='display_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='display_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
