# Generated by Django 5.0.3 on 2024-04-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_promotions_is_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='discount_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
