# Generated by Django 5.0.3 on 2024-04-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_promotions_discount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmresponses',
            name='response_html',
            field=models.TextField(null=True),
        ),
    ]
