# Generated by Django 5.0.3 on 2024-04-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_llmresponses_response_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='image_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
